[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_APP_URL = "https://your-site.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
